name: Tests

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

jobs:
  pest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpVersion: ['8.2', '8.3', '8.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpVersion }}
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Pest tests
        run: ./vendor/bin/pest
